version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: leetcode_db
    environment:
      POSTGRES_DB: leetcode
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - 5432:5432
    volumes:
      - leetcode_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  judge0:
    image: judge0/judge0:1.13.1
    container_name: judge0
    volumes:
      - /tmp/judge0-testcases:/tmp/judge0-testcases
    ports:
      - "2358:2358"
    privileged: true
    restart: unless-stopped
    environment:
      WORKERS: 1
      MAX_QUEUE_SIZE: 10000
      ENABLE_WAIT_RESULT: "true"
    depends_on:
      - postgres

volumes:
  leetcode_db_data:
