version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: leetcode_db
    environment:
      POSTGRES_DB: leetcode
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - 5432:5432
    volumes:
      - leetcode_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  leetcode_db_data: